trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: gitmirror@0
  inputs:
    GitRepoUrl: 'https://ikjmrgdvjhc2ze542knititnzvekeiuas3n4tgd4paowguvyeula@dev.azure.com/walterQian/Case/_git/yamltest.git'
